import sys
import os
import bz2
import ipaddress
from datetime import datetime
import logging as log 
import multiprocessing as mp
from tqdm import tqdm

NPROC = 30
CHUCK_SIZE = 50000
now = datetime.now().strftime("%Y%m%d-%H%M%S")
outfile_name = "non_slaac_" + now + ".csv"

'''
check if an address is SLAAC-generated by checking if
EUI-64 is present
    @addr: full expanded ipv6 address without colons
'''
def is_slaac(addr):
    return addr[22:26].lower() == "fffe"

'''
return network ID and host ID of an address
    @addr: full expanded ipv6 address without colons
'''
def split_ip(addr):
    return addr[:16], addr[16:]

'''
filter out addresses generated by SLAAC
'''
def write_non_slaac(chunk):
    loc_total = 0
    loc_slaac_total = 0
    loc_host_dict = defaultdict(list)
    loc_nslaac_lst = []

    for line in chunk:
        tokens = line.split(",")
        if not len(tokens) == 7:
            log.warning("Malformed input data line, skipping")
            continue
        # expand address
        src_ip_str = tokens[2].strip()
        src_ip_obj = ipaddress.IPv6Address(src_ip_str)
        full_addr = src_ip_obj.exploded.replace(":", "")
        # filter out slaac addresses
        if is_slaac(full_addr):
            loc_slaac_total += 1
        else:
            loc_nslaac_lst.append(line)
            network_id, host_id = split_ip(full_addr)
            loc_host_dict[host_id].append(network_id)
        loc_total += 1

    loc_nslaac_total = loc_total - loc_slaac_total
    return loc_nslaac_lst, loc_nslaac_total, loc_host_dict

'''
process all data
main process hands chucks to worker processes
'''
def main():

    # get and validate names of input files
    if len(sys.argv) < 2:
        print("Usage: python3 filter.py <input1.csv.bz2> <input2.csv.bz2> ...")
        sys.exit(1)
    for filepath in sys.argv[1:]:
        if not os.path.exists(filepath):
            log.error(f"{filepath} not found, please double check")
            sys.exit(1)

    grand_total = 0                    # total number of addr
    grand_slaac_total = 0              # total number of slaac addr

    pool = mp.Pool(NPROC)              # create workers
    host_dict = mp.Manager().dict()    # create shared dictionary
    outfile = open(outfile_name, "w")  # create shared output file

    for filepath in sys.argv[1:]:
        log.info(f"Started processing [{filepath}]")
        file_total = 0
        file_slaac_total = 0
        curr_chuck = []
        result_objs = []

        infile = bz2.open(filepath, "rt")
        for line in infile:
            line = line.strip()
            if line.startswith("#"): continue
            if len(curr_chuck) <= CHUCK_SIZE:
                curr_chuck.append(line)
            else:
                result = pool.apply_async(write_non_slaac, (curr_chuck,))
                result_objs.append(result)
                curr_chuck = []
                for ro in result_objs:
                    loc_nslaac_lst, loc_nslaac_total, loc_host_dict = ro.get()

        infile.close()
        log.info(f"Finished processing [{filepath}]")

    outfile.close()
    pool.close()

if __name__ == "__main__":
    main()