import sys
import os
import bz2
import ipaddress
import time
from datetime import datetime
import logging as log 
import multiprocessing as mp
from tqdm import tqdm
from pb_amarder import Progress
from collections import defaultdict, Counter

NPROC = 30
CHUCK_SIZE = 50000
now = datetime.now().strftime("%Y%m%d_%H%M%S")
nslaac_filename = "non_slaac_" + now + ".csv"

'''
check if an address is SLAAC-generated by checking if
EUI-64 marker (FFFE) is present
    @addr: full expanded ipv6 address without colons
'''
def is_slaac(addr):
    return addr[22:26].lower() == "fffe"

'''
return network ID and host ID of an address
    @addr: full expanded ipv6 address without colons
'''
def split_ip(addr):
    return addr[:16], addr[16:]

'''
filter out addresses generated with SLAAC by chunk
    @chunk: one partition of the full file, handled by one worker
'''
def write_non_slaac(chunk):
    loc_total = 0
    loc_nslaac_total = 0
    loc_host_dict = defaultdict(list)
    loc_host_counter = Counter()
    loc_nslaac_lines = []

    for line in chunk:
        parts = line.split(",")
        if not len(parts) == 7:
            log.warning("Malformed input data line, skipping")
            continue
        # expand address
        src_ip_str = parts[2].strip()
        # TODO what do we do if the responding router has a v4 address?
        #   we probably should skip since we only care about slaac, right?
        try:
            src_ip_obj = ipaddress.IPv6Address(src_ip_str)
        except:
            # log.warning(f"Responding router {src_ip_str} has a v4 address")
            continue
        full_addr = src_ip_obj.exploded.replace(":", "")

        # filter out slaac addresses
        if is_slaac(full_addr):
            continue
        else:
            loc_nslaac_total += 1
            loc_nslaac_lines.append(line)
            network_id, host_id = split_ip(full_addr)
            loc_host_dict[host_id].append(network_id)
            loc_host_counter[host_id] += 1
        loc_total += 1

    return loc_nslaac_lines, loc_total, loc_nslaac_total, loc_host_dict, loc_host_counter

'''
process all data
main process hands chucks to worker processes
'''
def main():
    # get and validate names of input files
    if len(sys.argv) < 2:
        print("Usage: python3 filter.py <input1.csv.bz2> <input2.csv.bz2> ...")
        sys.exit(1)
    for filepath in sys.argv[1:]:
        if not os.path.exists(filepath):
            log.error(f"{filepath} not found, please double check the name")
            sys.exit(1)
        if not (filepath.endswith(".csv.bz2") or filepath.endswith(".csv")):
            log.error("Invalid file format. It should only end with .csv or .csv.bz2")
            sys.exit(1)

    grand_total = 0                       # total number of addr
    grand_nslaac_total = 0                # total number of non-slaac addr
    grand_host_dict = defaultdict(list)   # dictionary (key: host_id, value: list of network_id)
    grand_host_counter = Counter()        # counter (key: host_id, value: times repeated)
    tqdm.set_lock(mp.RLock())
    pool = mp.Pool(NPROC, initializer=tqdm.set_lock, initargs=(tqdm.get_lock(),))
    outfile = open(nslaac_filename, "w")  # create output file
    start_time = time.perf_counter()

    for filepath in sys.argv[1:]:
        if filepath.endswith(".csv"):
            open_func = open
        else:
            open_func = bz2.open
        
        curr_chuck = []
        worker_rets = []

        log.info(f"Started processing [{filepath}]")
        infile = open_func(filepath, "rt")
        for line in infile:
            line = line.strip()
            if line.startswith("#"): continue
            if len(curr_chuck) <= CHUCK_SIZE:
                curr_chuck.append(line)
            else:
                wr = pool.apply_async(write_non_slaac, (curr_chuck,))
                worker_rets.append(wr)
                curr_chuck = []
        if curr_chuck:
            wr = pool.apply_async(write_non_slaac, (curr_chuck,))
            worker_rets.append(wr)
        
        # set pb for main process as it combines each worker's output
        aggregater_pb = Progress(len(worker_rets), callback=lambda: f"Collected results from {ret_count} workers")
        ret_count = 0
        for wr in aggregater_pb.iterator(worker_rets):
            ret_count += 1
            loc_nslaac_lines, loc_total, loc_nslaac_total, loc_host_dict, loc_host_counter = wr.get()
            outfile.write('\n'.join(loc_nslaac_lines)+'\n')
            grand_total += loc_total
            grand_nslaac_total += loc_nslaac_total
            for host_id, network_ids in loc_host_dict.items():
                grand_host_dict[host_id].extend(network_ids)
            grand_host_counter += loc_host_counter

        infile.close()
        log.info(f"Finished processing [{filepath}]")

    outfile.close()
    end_time = time.perf_counter()
    pool.close()

    print(f"\nSUMMARY")
    print("="*55)
    print(f"Number of worker processes used {NPROC}")
    print(f"Files processed in {end_time - start_time} seconds")
    print(f"Total number of addresses processed: {grand_total}")
    print(f"Total number of v6 non-SLAAC addresses: {grand_nslaac_total}")
    print(f"Percentage of non-SLAAC addresses out of all: {grand_nslaac_total / grand_total}")
    print(f"\nTop 20 most repeated host addresses")
    print(f"  {'Count':>15}   {'Host ID':>30}")
    print(f"  {'-'*15}   {'-'*35}")
    for host_id, count in grand_host_counter.most_common(20):
        formatted = f"{host_id[0:4]}:{host_id[4:8]}:{host_id[8:12]}:{host_id[12:16]}"
        print(f"  {count:>15,}    {formatted:>35}")
        
if __name__ == "__main__":
    main()